# Generated by Django 4.2.7 on 2023-11-27 10:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tradeboard", "0003_item_alter_rating_rating"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Item",
        ),
    ]
